### ISSUE TITLE
E0611:No name 'urlresolvers' in module 'django.core'

### ISSUE THREAD

**Issue by cgoss** [gitgik/django-rest-api#2]
in your tutorial I get an error when I get to the test for the views at the end. 
linter gives this error. 

E0611:No name 'urlresolvers' in module 'django.core'

**Comment by gitgik** [comment]
What version of Django are you using? It appears that Django 2.0 removed the django.core.urlresolvers module, which was moved to django.urlsin version 1.9. You should change any import to use django.urls instead.
Note that Django 2.0 removes some features that previously were in django.core.urlresolvers, so you might have to make some more changes before your code works.

Jee Githinji Gikera / Andela.com
Whimsical Software Engineer / 0711491852 / @Andela

"The startup that's harder to get into than Harvard" - CNN
See what The Wall Street Journal has to say.

**Comment by cgoss** [comment]
I just found the release notes on version 2.0. It looks like they moved the urlresolvers namespace under django.urls. 

Updating the include to the new location makes the tests move onto the next error. 

There is an error in the test can update a bucket list, this is minor and I think i got it figured out. 

Thanks for the help.

**Comment by gitgik** [comment]
Much obliged @cgoss  :-)

Jee Githinji Gikera / Andela.com
Whimsical Software Engineer / 0711491852 / @Andela

"The startup that's harder to get into than Harvard" - CNN
See what The Wall Street Journal has to say.
